server:
  port: 9091
  servlet:
    context-path: /


spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    timeout: 6000ms
    password: qwer944610721
    #高可用 哨兵-主从架构
    cluster:
      nodes: 121.199.71.179:6391,121.199.71.179:6392,121.199.71.179:6393,121.199.71.179:6394,121.199.71.179:6395,121.199.71.179:6396
    lettuce:
      pool:
        max-active: 200  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）


# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别  error、warn、info、debug、trace、all
    root: info
  file:
    name: logfile/redis/prod/redis.log