server:
  port: 8092
  servlet:
    context-path: /



# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别  error、warn、info、debug、trace、all
    root: info
  file:
    path: logfile/rocketmq/rocketmq.log