server:
  port: 9091
  servlet:
    context-path: /


spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 10
    timeout: 6000ms
    password: 123456
    #高可用 哨兵-主从架构
    sentinel:
      master: mymaster
      nodes: 192.168.64.208:26379,192.168.64.208:26380,192.168.64.208:26381
    lettuce:
      pool:
        max-active: 200  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）


# slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别  error、warn、info、debug、trace、all
    root: info
  # 在不指定路径，只指定输出日志的文件名，默认输出至当前项目下
  # 若指定，则会输出至指定目录下
  file: log/redis/redis.log